neos/form

- Resources/Private/Form/StaticText.html
Only output ``element.properties.text`` if set. 
Otherwise the result might be an empty ``<p>`` tag within the form.
FLOW-375 #close
> BUGFIX: Check if property ``text`` exists

- Configuration/Settings.yaml
- Resources/Private/Form/SingleSelectDropdown.html
This makes the class attribute in the template for
TYPO3.Form:SingleSelectDropdown configurable like
in every other field element template.
> BUGFIX: Make class in SingleSelectDropdown configurable

- Classes/TYPO3/Form/ViewHelpers/Form/DatePickerViewHelper.php
Currently the date selector uses jQuery UI for the date selector.
This PR changes the field type for the date selector to "date"
to enable the HTML5 date selector as soon you disable the
jQuery script.
> TASK: Change field type to date to enable HTML5 date selector

- Classes/TYPO3/Form/ViewHelpers/RenderViewHelper.php
This avoids a syntax error in the auto-generated rST ViewHelper reference.
> TASK: Fix docblock to avoid rST syntax errors

- Classes/TYPO3/Form/ViewHelpers/TranslateElementPropertyViewHelper.php
- Configuration/Settings.yaml
- Documentation/index.rst
- Documentation/translating-forms.rst
- Migrations/Code/Version20160601101500.php
- Resources/Private/Form/DatePicker.html
- Resources/Private/Form/FileUpload.html
- Resources/Private/Form/ImageUpload.html
- Resources/Private/Form/Layouts/Field.html
- Resources/Private/Form/MultiLineText.html
- Resources/Private/Form/MultipleSelectCheckboxes.html
- Resources/Private/Form/MultipleSelectDropdown.html
- Resources/Private/Form/Page.html
- Resources/Private/Form/Partials/Form/Navigation.html
- Resources/Private/Form/Password.html
- Resources/Private/Form/PasswordWithConfirmation.html
- Resources/Private/Form/PreviewPage.html
- Resources/Private/Form/Section.html
- Resources/Private/Form/SingleLineText.html
- Resources/Private/Form/SingleSelectDropdown.html
- Resources/Private/Form/SingleSelectRadiobuttons.html
- Resources/Private/Form/StaticText.html
- Resources/Private/Translations/de/Main.xlf
- Resources/Private/Translations/en/Main.xlf
- composer.json
This change allows for forms to be translated using XLIFF as elsewhere
in Flow. Form element labels, placeholders, option labels and more can
be translated.
Instructions are included in a new documentation chapter.
This is marked as breaking: if you changed the "translationPackage"
earlier to customize validation error messages, you will need to use the
new "validationErrorTranslationPackage" setting for that now. A code
migration to adjust that is included, run:
./flow flow:core:migrate  --version 20160601101500 --package-key ...
> !!! FEATURE: Translatable forms

- Classes/TYPO3/Form/Finishers/RedirectFinisher.php
This change adds the option to allow a specific URL
to be set for the redirect finisher. Also some cleanup /
refactoring is done.
> FEATURE: Allow to set a specific URL for the redirect finisher

- Classes/TYPO3/Form/ViewHelpers/RenderHeadViewHelper.php
Removes usage of deprecated ``ResourcePublisher`` in favor of
the ``ResourceManager`` to get URIs for static resources.
> TASK: Adapt to ``ResourceManager``

- Classes/Finishers/EmailFinisher.php
Sometimes it is handy to know from which URL a form email was sent,
especially if no external tracking like GA or Piwik is in place.
The referrer can be inserted into the Fluid template using the following
notation: {referrer}.
> FEATURE: Make the referrer of the form available in Fluid template

- Classes/Finishers/EmailFinisher.php
This replaces the arguments “recipientName” and “recipientAddress” with
a more generic array argument “recipients”.
Addresses and corresponding names can be entered with key => value,
single addresses as single array values.
This means that the YAML configuration must be updated accordingly:
…
recipients:
‘recipient.one@example.com’: ‘Recipient One’
‘recipient.two@example.com’: ‘Recipient Two’
…
The following notation also works (if just one recipient is desired):
…
recipients: {email}
…
> FEATURE: Support multiple recipients in EmailFinisher

- Classes/TYPO3/Form/ViewHelpers/Form/DatePickerViewHelper.php
This reduces the risk of collision in auto-generated field names.
> TASK: Use generateRandomString() instead of uniqid()

- Migrations/Code/Version20160601101500.php
With the namespace change the code migration `TYPO3.Form-20160601101500` has not
been adjusted completely, see: https://github.com/neos/form/commit/dfa23c6561e3e5877b8d15197204f8811b1921d3#commitcomment-21736520
As a result, it adds new `TYPO3.Form.*` settings if the settings have been adjusted
to the new namespace (`Neos.Form.*`) already.
This change fixes this.
Fixes: #42
> BUGFIX: Fix code migration

- Classes/FormElements/DatePicker.php
The date format of the custom `DatePicker` Form Element
can be changed via the `dateFormat` property.
Previously this setting was ignored in the property mapping
of the date though, so the DatePicker didn't work unless
the date was pre-processed via JavaScript
> BUGFIX: Respect custom date formats in the DatePicker

- Classes/FormElements/FileUpload.php
- Classes/FormElements/ImageUpload.php
Previously the validation rules for the custom Form Elements
`FileUpload` and `ImageUpload` were configured upon Form Element
initialization.
This had the side effect that changes to the configuration
(e.g. to the "allowedExtensions") that were made at runtime (i.e
not in the form preset) were ignored.
> BUGFIX: Defer upload validation to form submission

- Classes/Core/Runtime/FormRuntime.php
- Classes/ViewHelpers/FormViewHelper.php
The serialized form state is passed through the form pages
so that the form values can't be altered.
This change moves the state serialization from the `FormViewHelper`
to the `FormRuntime` so that it can be reused from other renderers.
> TASK: Expose serialized form state from the Form runtime

- Classes/Core/Renderer/FluidFormRenderer.php
- Classes/Core/Runtime/FormRuntime.php
- Documentation/extending-form-api.rst
Adds an API method `registerRenderCallback()` to the `FormRuntime`
that allows for influencing the rendering of rendered elements.
Usage:
$formRuntime->registerRenderCallback(function (string $output, RootRenderableInterface $renderable) {
return $renderable->getIdentifier() . ': ' . $output;
});
This simple example will render the Element identifier in front of every form
element, independantly from the configured Form (Element) Renderer.
Background:
The rendering of Form Elements can already be configured and altered
thoroughly, but this allows for 3rd party integration. For example we can
use this to wrap each Form Element using the `ContentElementWrappingService`
in order to render the required wraps in the Neos Backend.
> FEATURE: Configurable Form Element render callbacks

- Configuration/Settings.yaml
- Resources/Private/Form/FormEditMode.html
This change adds a new Form Element definition
`Neos.Form:FormEditMode` to the `default` preset that
allows to render the form in an "edit mode" (which usually
displays all form pages and can disable certain interactions
that would affect the UX of form builders)
> TASK: FormEditMode Form Element preset

- Classes/Finishers/EmailFinisher.php
- Documentation/configuring-form-yaml.rst
Extends the `EmailFinisher` to be able to send files
(uploaded via the form or static ones) as attachment(s).
Usage:
```yaml
finishers:
-
identifier: 'Neos.Form:Email'
options:
attachAllPersistentResources: true
```
This would attach files from all FormElements with dataType `PersistentResource` (e.g. the `FileUpload` element defined in the `default` preset)
```yaml
finishers:
-
identifier: 'Neos.Form:Email'
options:
attachments:
- resource: 'resource://Some.Vendor:Package/Some/Path/To/A/File'
- formElement: 'some-upload-field'
```
This would attach a static file, referenced via the `resource` option and an uploaded
file (if the element `some-upload-field` exists in that form and contains a `PersistentResource`).
This change also improves the exception message that is thrown if the …
> FEATURE: EmailFinisher file attachments

- Classes/ViewHelpers/Form/UploadedImageViewHelper.php
- Resources/Private/Form/ImageUpload.html
Adjusts the Fluid Template for the `ImageUpload` field (and the corresponding
ViewHelper) to make the upload work again with latest Flow/Neos versions
> BUGFIX: Fix `ImageUpload` FormElement rendering

- Classes/Finishers/EmailFinisher.php
- Documentation/configuring-form-yaml.rst
This adds a new option `templateSource` to the `EmailFinisher`
that allows the Fluid template to be specified directly.
Besides this makes all submitted form values accessible within
the EmailFinisher template as `formValues`::
finishers:
-
identifier: 'Neos.Form:Email'
options:
templateSource: 'Hello {formValues.name}, ...'
> FEATURE: Allow the EmailFinisher template source to be set

- Classes/ViewHelpers/RenderViewHelper.php
When using the `RenderViewHelper` without specifying the `overrideConfiguration`
argument, a fatal error is thrown.
This patch prevents this by making the default value of the argument an empty
array.
Fixes: #7
> BUGFIX: Prevent fatal error when using the RenderViewHelper

- Configuration/Settings.yaml
It is a wrong Neos in the Settings.yaml which overwrites the configuration above.
> BUGFIX: Remove wrong "Neos" in Settings.yaml

- Resources/Private/Form/Layouts/Field.html
The `Form\ValidationResultsViewHelper` was 
deprecated since Flow 2.1 and shouldn't be used anymore.
> TASK: Use correct validation `ResultsViewHelper`

- Classes/Finishers/EmailFinisher.php
The addAttachment ran into trouble when it tired to iterate over en attachments configuration that was not set at all. The change adds a beforehand check that the attachments configuration is set.
> BUGFIX: Evaluate attachment configuration only if present

- Classes/Factory/ArrayFormFactory.php
For the creation of atomic rendered forms in the upcoming package https://github.com/1drop/Onedrop.Form.Hubspot i need to override the default `neos:Form:Form` form type with my own form type. To achieve this the configuration of the form should be usable.
Background: With the `ArrayFormFactory` i can create forms by defining them as an array. I can control the type of any created sub element (renderable) by passing `type` in the configuration for that element. The only place where this is currently not possible is the root element (the `FormDefinition`). Therefor i chose to read the type from the configuration array.
This does not change any signature, so it is not a BC but fully backwards compatible.
> TASK: Allow the configuration of the form type

- Classes/Core/Runtime/FormRuntime.php
This fixes `FormRuntime::render()` to bubble up response
headers to the parent response.
This will make sure that any headers that have been set by
finishers (e.g. the `Location`-header in the `RedirectFinisher`)
are actually taken into account.
Fixes: #84
> BUGFIX: Don't ignore response headers when rendering a form

- Classes/Finishers/EmailFinisher.php
Because parseOption() now returns null for empty/not-set options, the
comparison of $recipientName with an empty string woud trigger an exception
when passing multiple recipients via $recipientAddress, even though this
usage is legal.
Fixes: #77
> #77: Fix a false error when using recipientAddress as array

- Classes/ViewHelpers/Form/DatePickerViewHelper.php
- Classes/ViewHelpers/Form/FormElementRootlinePathViewHelper.php
- Classes/ViewHelpers/Form/UploadedImageViewHelper.php
- Classes/ViewHelpers/Form/UploadedResourceViewHelper.php
- Classes/ViewHelpers/RenderHeadViewHelper.php
- Classes/ViewHelpers/RenderRenderableViewHelper.php
- Classes/ViewHelpers/RenderValuesViewHelper.php
- Classes/ViewHelpers/RenderViewHelper.php
- Classes/ViewHelpers/TranslateElementPropertyViewHelper.php
- Tests/Functional/AbstractFunctionalTestCase.php
This removes the arguments from `render()` in Fluid ViewHelpers, and
registers them using `registerArgument` instead.
Arguments to `render()` were deprecated as of Flow 4.0 and support
is removed with Flow 6.0.
> TASK: Remove arguments from VH render methods

- Classes/Finishers/EmailFinisher.php
Starting with version 6.0 Swiftmailer [removed newInstance() methods everywhere](https://github.com/swiftmailer/swiftmailer/blob/74e20ce4dad5011fb2c2cedefb76b2237f123c0e/CHANGES#L14).
This change reflects this change to support Swiftmailer >= v6.
> FEATURE: Adds support for swiftmailer >= v6.0

- Classes/Core/Model/ProcessingRule.php
- Tests/Unit/Core/Model/ProcessingRuleTest.php
Injecting prototype scoped objects prevents deserialization and thus
caching of a form definition (which is helpful with larger node based
forms).
Closes #94
> Bugfix: Do not inject prototype scoped objects

- Classes/Finishers/FlashMessageFinisher.php
`parseOption()` unfortunately returns `null` if the option value is an empty string.
Since 6.0, `Message` doesn't accept `null` values for the title argument anymore.
> BUGFIX: Message constructor needs title to be string

- Tests/Unit/Core/Model/PageTest.php
Test would fail due to unexpected validator option `"ignoreHtml"`.
See https://github.com/neos/flow-development-collection/pull/1849
> TASK: Adjust test to StringLengthValidator change

- Classes/Finishers/EmailFinisher.php
Previously the `EmailFinisher` threw an exception when using
attachments and a `swiftmailer/swiftmailer` version 6+:
Call to undefined method Swift_Attachment::newInstance()
This is fixed with this change. Older SwiftMailer versions
are still supported.
Resolves: #112
> FEATURE: Support SwiftMailer 6.x

- Classes/FormElements/FileUpload.php
- Configuration/Settings.yaml
- Resources/Private/Form/FileUpload.html
This feature extends the `FileUpload` Form element such that
the target Resource Collection can be configured.
This can be useful for example in order to prevent uploaded
files to end up in the public "persistent" collection:
Neos:
Flow:
resource:
targets:
'formUploadTarget':
target: 'Some\Package\SomeProtectedResourceTarget'
collections:
'formUploads':
storage: 'defaultPersistentResourcesStorage'
target: 'formUploadTarget'
Form:
presets:
'default':
formElementTypes:
'Neos.Form:FileUpload':
properties:
resourceCollection: 'formUploads'
createLinkToFilePreview: false
Thanks to internezzo ag for sponsoring this feature!
Resolves: #114
> FEATURE: Configurable Resource Collection for file uploads

- Classes/Finishers/EmailFinisher.php
At the moment it is not possible to send multipart mails with the EmailFinisher.
This PR adds 4 new options:
* htmlTemplatePathAndFilename
* htmlTemplateSource
* plaintextTemplatePathAndFilename
* plaintextTemplateSource
A new format constant `FORMAT_MULTIPART` is introduced.
Example form config:
```yaml
type: 'Neos.Form:Form'
identifier: 'contact'
label: 'Contact form'
renderables:
-
type: 'Neos.Form:Page'
identifier: 'page-one'
renderables:
...
finishers:
-
identifier: 'Neos.Form:Email'
options:
plaintextTemplatePathAndFilename: resource://AcmeCom.SomePackage/Private/Templates/Form/Contact.txt
htmlTemplatePathAndFilename: resource://AcmeCom.SomePackage/Private/Templates/Form/Contact.html
subject: '{subject}'
recipientAddress: 'info@acme.com'
recipientName: 'Acme Customer Care' …
```
> FEATURE: send multipart mail with EmailFinisher

- Classes/Finishers/EmailFinisher.php
Adjusts the `EmailFinisher` so that formValues are available as placeholders
directly (i.e. without requiring the `formValues.*` prefix).
That allows the `EmailFinisher` to be used the same way as the `ConfirmationFinisher`.
Note: This change is backwards compatible since the `formValues.` prefix is
still supported.
Resolves: #121
> FEATURE: Make FormValues directly available in EmailFinisher template

- Classes/ViewHelpers/Form/UploadedImageViewHelper.php
The way the property mapping works, instead of Image an ImageVariant
can be returned. To make this non-breaking, the return type of
`getUploadedImage()` is relaxed.
Fixes #119
> BUGFIX: Allow ImageInterface to be returned in UploadedImageViewHelper

- Classes/Finishers/EmailFinisher.php
Fixes https://github.com/neos/form/issues/124
> BUGFIX: Remove void return type to stay compabible with PHP 7.0

- Classes/ViewHelpers/RenderValuesViewHelper.php
We got problems with forms using select-lists with customized options, when they are optional and broke it down to this method while debugging. 
When the input is optional and not selected, both (`$options[$value]` and `$value`) where empty (`NULL`) in our cases.  
Since the method-signature requires the method to return a string, this fails with `Return value of Neos\Form\ViewHelpers\RenderValuesViewHelper_Original::mapValueToOption() must be of the type string, null returned`.   
Probably this was introduced with the strict-types declaration 
I solved it by simply adding an empty string as fallback-value here and think that should also get into the Neos.Form-Core.
> BUGFIX: mapValueToOption should always return string

- Classes/Core/Runtime/FormRuntime.php
- Tests/Functional/Fixtures/FormFactories/TwoPageFormWithUploadFactory.php
- Tests/Functional/Fixtures/dummy.txt
- Tests/Functional/SimpleFormTest.php
This fixes a regression introduced with #101 that prevented
objects like images and documents to be persisted in the
Form State, leading to exceptions in multi step forms.
Fixes: #143
Related: #126 #135
> BUGFIX: Allow arbitrary objects in the FormState

- Classes/Core/Model/Renderable/AbstractCompositeRenderable.php
- Tests/Unit/Core/Model/FormDefinitionTest.php
Removing a renderable should set index of renderables as move does
Fixes neos/form#150
> BUGFIX: Reindex renderables on remove

- Classes/Core/Runtime/FormRuntime.php
Form Pages are an instance of `AbstractSection` but their `onSubmit()`
callback was never invoked by the Form Framework.
Resolves: #148
> FEATURE: Invoke onSubmit callback on pages

- .github/workflows/tests.yml
- Classes/Core/Model/FormDefinition.php
- Classes/Core/Runtime/FormRuntime.php
- Classes/FormState/DefaultFormStateInitializer.php
- Classes/FormState/FormStateInitializerInterface.php
- Configuration/Settings.yaml
- composer.json
This adds a mechanism to hook into the form state initialization and define custom initializers.
Resolves: #152
> FEATURE: Make formState initialization extendable

- Classes/Core/Runtime/FormRuntime.php
Fixes a regression that was introduced with #149 that led to `onSubmit()` callbacks to only get hold of the form state of previous pages.
With this fix `$formRuntime->getFormState()->getFormValues()` in a custom element will return the previously handled form values, even of the current form page.
Fixes: #156
> BUGFIX: Update form state upon element submission

- Classes/Core/Runtime/FormState.php
The `FormState` is not meant to be subclassed.
This is now enforced via the PHP type system.
Resolves: #128
> TASK: Make `FormState` a final class

- Classes/Core/Model/AbstractFormElement.php
- Classes/Core/Model/FormElementInterface.php
- Classes/Core/Model/Renderable/AbstractRenderable.php
- Classes/Core/Model/UnknownFormElement.php
- Classes/FormElements/Section.php
- Add getRenderingOption-Function to the AbstractRenderable-Model
- Add getProperty-Function to FormElement
Those functions are helpful for Custom Form Elements to get simpler access to a property or rendering option.
> !!! FEATURE: Add getProperty to FormElement & add getRenderingOption to AbstractRenderable

- Classes/ViewHelpers/RenderValuesViewHelper.php
Adjusts the `RenderValuesViewHelper` such that it checks whether the element value to render is an object, _before_ trying to map it.
This resolves an `Illegal offset type` exception that was thrown for `\DateTime` objects with PHP > 7.4
> BUGFIX: Fix RenderValuesViewHelper PHP 8+ compatibility

- .github/workflows/tests.yml
- Classes/Core/Model/FormDefinition.php
- Classes/Core/Runtime/FormRuntime.php
- Classes/Finishers/FlashMessageFinisher.php
- composer.json
Fixes warnings like:
`Return type of Neos\Form\Core\Runtime\FormRuntime::offsetUnset($identifier) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`
> TASK: Fix warnings with PHP 8 about incompatible (return) types

- .github/workflows/tests.yml
- Classes/Finishers/EmailFinisher.php
- Tests/Functional/AbstractFunctionalTestCase.php
- composer.json
Replaces the neos/swiftmailer with neos/symfonymailer.
To prevent a hard dependency to the neos/symfonymailer package, the MailerService is fetched directly from the object manager. The ProxyBuilding doesn't allow any injection without the class existing.
> !!! FEATURE: Replace neos/swiftmailer with neos/symfonymailer

- Classes/ViewHelpers/Form/TimePickerViewHelper.php
To get rid of PHP 8.4 deprecation warnings
> BUGFIX: Explicit marking of nullable parameter

- Classes/Finishers/EmailFinisher.php
We had issues with the mail finisher not adding the images added by the `Neos.Form.Builder:ImageUpload`
This will include the uploaded image in the mail when `attachAllPersistentResources` option is checked
> BUGFIX: send uploaded images as mail attachments
